# Document engine configuration

# Initialize engine-specific variables
set(APVLV_ENGINE_HEADERS "")
set(APVLV_ENGINE_SOURCES "")
set(APVLV_ENGINE_LIBRARIES "")

# MuPDF engine
if(APVLV_WITH_MUPDF)
  message(STATUS "Enable MuPDF engine")
  list(APPEND APVLV_ENGINE_HEADERS file/ApvlvMuPdf.h)
  list(APPEND APVLV_ENGINE_SOURCES file/ApvlvMuPdf.cc)

  if(WIN32)
    if(MUPDF_FOUND)
      if(TARGET mupdf::mupdf)
        list(APPEND APVLV_ENGINE_LIBRARIES mupdf::mupdf)
      elseif(MUPDF_STATIC_LIBRARIES)
        list(APPEND APVLV_ENGINE_LIBRARIES ${MUPDF_STATIC_LIBRARIES})
      else()
        list(APPEND APVLV_ENGINE_LIBRARIES mupdf)
      endif()
    else()
      # Fallback to direct library name
      list(APPEND APVLV_ENGINE_LIBRARIES mupdf)
    endif()
  else()
    if(MUPDF_FOUND)
      list(APPEND APVLV_ENGINE_LIBRARIES ${MUPDF_STATIC_LIBRARIES} -lharfbuzz)
    else()
      list(APPEND APVLV_ENGINE_LIBRARIES -lmupdf)
    endif()
  endif()
endif()

# Poppler engine
if(APVLV_WITH_POPPLER)
  if(WIN32)
    # On Windows, Poppler is enabled by default
    message(STATUS "Enable Poppler engine")
    list(APPEND APVLV_ENGINE_HEADERS file/ApvlvPopplerPdf.h)
    list(APPEND APVLV_ENGINE_SOURCES file/ApvlvPopplerPdf.cc)
    if(POPPLER_FOUND)
      if(TARGET Poppler::poppler)
        list(APPEND APVLV_ENGINE_LIBRARIES Poppler::poppler)
      elseif(POPPLER_LIBRARIES)
        list(APPEND APVLV_ENGINE_LIBRARIES ${POPPLER_LIBRARIES})
      else()
        list(APPEND APVLV_ENGINE_LIBRARIES poppler)
      endif()
    else()
      # Fallback to direct library name
      list(APPEND APVLV_ENGINE_LIBRARIES poppler)
    endif()
  elseif()
    message(STATUS "Enable Poppler engine")
    include_directories(${POPPLER_INCLUDE_DIRS})
    list(APPEND APVLV_ENGINE_HEADERS file/ApvlvPopplerPdf.h)
    list(APPEND APVLV_ENGINE_SOURCES file/ApvlvPopplerPdf.cc)
    list(APPEND APVLV_ENGINE_LIBRARIES ${POPPLER_LIBRARIES})
  endif()
endif()

# DjVu support
if(APVLV_WITH_DJVU)
  message(STATUS "Enable DjVu support")
  list(APPEND APVLV_ENGINE_HEADERS file/ApvlvDjvu.h)
  list(APPEND APVLV_ENGINE_SOURCES file/ApvlvDjvu.cc)

  if(WIN32)
    if(TARGET djvulibre::djvulibre)
      list(APPEND APVLV_ENGINE_LIBRARIES djvulibre::djvulibre)
    elseif(DJVULIBRE_DIR)
      include_directories(${DJVULIBRE_DIR}/include)
      link_directories(${DJVULIBRE_DIR}/lib)
      list(APPEND APVLV_ENGINE_LIBRARIES djvulibre)
    else()
      # Fallback to direct library name
      list(APPEND APVLV_ENGINE_LIBRARIES djvulibre)
    endif()
  else()
    list(APPEND APVLV_ENGINE_LIBRARIES -ldjvulibre)
  endif()
endif()

# OCR support
if(APVLV_WITH_OCR)
  message(STATUS "Enable OCR support")
  add_definitions(-DAPVLV_WITH_OCR)
  list(APPEND APVLV_ENGINE_HEADERS ApvlvOCR.h)
  list(APPEND APVLV_ENGINE_SOURCES ApvlvOCR.cc)

  if(WIN32)
    if(TESSERACT_FOUND)
      if(TARGET tesseract::tesseract)
        list(APPEND APVLV_ENGINE_LIBRARIES tesseract::tesseract)
      elseif(TESSERACT_LIBRARIES)
        list(APPEND APVLV_ENGINE_LIBRARIES ${TESSERACT_LIBRARIES})
      else()
        list(APPEND APVLV_ENGINE_LIBRARIES tesseract)
      endif()
    else()
      # Fallback to direct library name
      list(APPEND APVLV_ENGINE_LIBRARIES tesseract)
    endif()
  else()
    if(TESSERACT_FOUND)
      list(APPEND APVLV_ENGINE_LIBRARIES ${TESSERACT_LIBRARIES})
    endif()
  endif()
endif()
