# Windows-specific document engines

if(WIN32 AND APVLV_WITH_OFFICE)
    message(STATUS "Enable MSOffice as office file engine")
    find_package(Qt6 REQUIRED COMPONENTS AxContainer)
    list(APPEND APVLV_ENGINE_LIBRARIES Qt6::AxContainer Shlwapi.lib)
    list(APPEND APVLV_ENGINE_HEADERS file/ApvlvAxOffice.h)
    list(APPEND APVLV_ENGINE_SOURCES file/ApvlvAxOffice.cc)
elseif(NOT WIN32 AND APVLV_WITH_OFFICE)
    message(STATUS "Enable libreOffice as office file engine")
    list(APPEND APVLV_ENGINE_LIBRARIES -llibreofficekitgtk)
    add_definitions(-DLIBO_INTERNAL_ONLY=1)
    list(APPEND APVLV_ENGINE_HEADERS file/ApvlvLibreOffice.h)
    list(APPEND APVLV_ENGINE_SOURCES file/ApvlvLibreOffice.cc)
endif()
